name: workflow-initial

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'  # speeds up subsequent builds

      # Step 3: Print Hello from Hexlet
      - name: Print Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release

      # Step 4: Install dependencies
      - name: Install dependencies
        run: make setup

      # Step 5: Run tests
      - name: Run tests
        run: make test

      # Step 6: Lint the code
      - name: Lint code
        run: make lint